### ISSUE TITLE
[14.0] registrar Pagos - Módulo de Ventas

### ISSUE THREAD

**Issue by luismata01** [odoo-mastercore/odoo-venezuela#13]
Cuando se trata de registrar un pago en el módulo de ventas al momento de cargar la línea en el Formulario Cargar Líneas de pago, cuando se selecciona el diario muestra el siguiente error, más sin embargo si desde el listado de facturas se selecciona la factura y se selecciona la acción PAgara factura, el proceso transcurre sin problemas.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 6240, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5982, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/auto/addons/l10n_ve_account_payment_fix/models/account_payment.py", line 192, in _onchange_journal
    if self.journal_id == self.destination_journal_id:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'account.payment' object has no attribute 'destination_journal_id'

**Comment by odoo-mastercore** [comment]
Hola  @luismata01 puedes asegurarte de que tienes el ultimo commit? nosotros no pudimos replicar tu error, si pudieras adjuntar una captura de pantalla para que nuestro equipo la evalué también, gracias.
