### ISSUE TITLE
Error al instalar Account UX en Odoo CE 16 - Localizacion Venezolana

### ISSUE THREAD

**Issue by fcachorro** [odoo-mastercore/odoo-venezuela#22]
Saludos, recibo este error al intentar instalar Account UX.

RPC_ERROR

Odoo Server Error

Traceback (most recent call last):
  File "C:\OdooCM\server\odoo\http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\OdooCM\server\odoo\service\model.py", line 133, in retrying
    result = func()
  File "C:\OdooCM\server\odoo\http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\OdooCM\server\odoo\http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\OdooCM\server\odoo\addons\website\models\ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "C:\OdooCM\server\odoo\addons\base\models\ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "C:\OdooCM\server\odoo\http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "C:\OdooCM\server\odoo\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\OdooCM\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\OdooCM\server\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\OdooCM\server\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "C:\OdooCM\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\OdooCM\server\odoo\addons\base\models\ir_module.py", line 468, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\OdooCM\server\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "C:\OdooCM\server\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "C:\OdooCM\server\odoo\modules\registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "C:\OdooCM\server\odoo\modules\loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "C:\OdooCM\server\odoo\modules\loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "C:\OdooCM\server\odoo\modules\loading.py", line 197, in load_module_graph
    model_names = registry.load(cr, package)
  File "C:\OdooCM\server\odoo\modules\registry.py", line 247, in load
    model = cls._build_model(self, cr)
  File "C:\OdooCM\server\odoo\models.py", line 615, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'account.account.type' does not exist in registry.

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://localhost:8069/web/assets/440-27044e7/web.assets_backend.min.js:981:274
    makeErrorFromResponse@http://localhost:8069/web/assets/440-27044e7/web.assets_backend.min.js:985:163
    jsonrpc/promise</<@http://localhost:8069/web/assets/440-27044e7/web.assets_backend.min.js:993:34

![image](https://github.com/odoo-mastercore/odoo-venezuela/assets/127030228/f8550e69-77cd-4201-8abb-4d8bf239111f)

![image](https://github.com/odoo-mastercore/odoo-venezuela/assets/127030228/00627d65-37b1-43bd-ab9b-557095ed8dab)

**Comment by rhe-mastercore** [comment]
Hola @fcachorro desde que repo lo estás instalando.? Nosotros tenemos un fork que le hicimos al proyecto original que está público en nuestra cuenta puedes tomarlo desde allí que ese está estable, slds.

**Comment by fcachorro** [comment]
Hola @rhe-mastercore y gracias por la pronta respuesta.

Lo tomé de acá
https://github.com/odoo-mastercore/account-financial-tools/tree/16.0

Que fue donde pude conseguirlo para V16, ya que los modulos de localización venezolana indican que hay dependencia de Account UX (entre otros, siendo esta la principal dependencia)
Quizas no era el correcto para esta versión de Odoo?
