### ISSUE TITLE
V16 CE  - Error al calcular las retenciones

### ISSUE THREAD

**Issue by pedrozam71** [odoo-mastercore/odoo-venezuela#23]
El siguiente error se genera al tratar de calcular las retenciones IVA de un pago a proveedor.

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo-server/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-server/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/16.0/account_withholding_automatic/models/account_payment_group.py", line 93, in compute_withholdings
    ]).create_payment_withholdings(rec)
  File "/opt/odoo/.local/share/Odoo/addons/16.0/l10n_ve_withholding/models/account_tax.py", line 332, in create_payment_withholdings
    if not journal:
UnboundLocalError: local variable 'journal' referenced before assignment

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://zmconsultores.online/web/assets/debug/web.assets_backend.js:10408:19) (/web/static/src/core/network/rpc_service.js:34)
    at XMLHttpRequest.<anonymous> (https://zmconsultores.online/web/assets/debug/web.assets_backend.js:10461:27) (/web/static/src/core/network/rpc_service.js:87)

**Comment by pedrozam71** [comment]
Con otra base de datos y en mismo modulo instalado, presenta este error.

![image](https://github.com/odoo-mastercore/odoo-venezuela/assets/70045892/38b3fb27-998c-4154-af29-8b174b043474)

**Comment by rhe-mastercore** [comment]
Hola @pedrozam71 gusto en saludarte, que bueno que utilices nuestro paquete de localización, mira lo que sucede por lo menos en la captura que me enviaste es que no tienes un libro de IVA ventas correctamente configurado para la retencio, slds.

**Comment by pedrozam71** [comment]
> Hola @pedrozam71 gusto en saludarte, que bueno que utilices nuestro paquete de localización, mira lo que sucede por lo menos en la captura que me enviaste es que no tienes un libro de IVA ventas correctamente configurado para la retencio, slds.

Mil gracias por tomarte el tiempo, revisar y responder a la brevedad. La localización de Venezuela desarrollada por ustedes me parece genial. Solo que no sé como configurar correctamente el libro de IVA. Tienen algún manual o tutorial que pueda seguir?

**Comment by pedrozam71** [comment]
> Hola @pedrozam71 gusto en saludarte, que bueno que utilices nuestro paquete de localización, mira lo que sucede por lo menos en la captura que me enviaste es que no tienes un libro de IVA ventas correctamente configurado para la retencio, slds.

Solucionado. Mil gracias.

![image](https://github.com/odoo-mastercore/odoo-venezuela/assets/70045892/0b36f279-1499-4540-a96f-e6d2f82a2ca8)
***
